###model
model_name_or_path: /root/autodl-tmp/LLaMA-Factory/Model_pre/Llama-3.2-11B-Vision-Instruct
template: mllama
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 8  


cutoff_len: 8192
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
###training
dataset: industrial_qa_cot_noregion
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

###output
output_dir: ./saves_cot/Llama-3.2-11B-Vision_lora_noregion
# export CUDA_VISIBLE_DEVICES=2 && llamafactory-cli train llama3_2_vision_lora_noregion.yaml
#  