###model
model_name_or_path: /root/autodl-tmp/LLaMA-Factory/Model_pre/llava1.5-7b
template: llava
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 8  


cutoff_len: 8192
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
###training
media_dir: /root/autodl-tmp/LLaMA-Factory
dataset: industrial_qa_without_cot
logging_steps: 10
save_steps: 3000
plot_loss: true
overwrite_output_dir: true

per_device_train_batch_size: 8
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 3000

###output
output_dir: /root/autodl-tmp/LLaMA-Factory/saves_cot/llava1.5-lora-nocot
# export CUDA_VISIBLE_DEVICES=0,1,2,3 && llamafactory-cli train qwen2.5_vl_lora.yaml
#  